Split functions into separate scripts

diff --git a/bin/notify-command b/bin/notify-command
--- a/bin/notify-command
+++ b/bin/notify-command
@@ -1,13 +1,30 @@
 #!/usr/bin/env bash
 # ──────────────────────────────────────────────────────────────────────────────────────────────────
 # Description
-#   Set recursively the svn:ignore rules defined in the file.
+#   Run a command and display a popup showing the success/failure.
 #
 # Arguments
-#   1 (optional) The file containing the svn:ignore rules.
-#
-# Dependencies
-#   * Commands: svn.
+#     @ (required) the command to run.
 # ──────────────────────────────────────────────────────────────────────────────────────────────────
 
-svn propset -R svn:ignore -F $1 .
+# Execute the command
+eval $@
+
+# Get the result
+result=$?
+
+# Try to use 'notify-send'
+if [ `which notify-send` ]; then
+  case $result in
+    0)
+      notify-send -i info "OK" "The command $@ ran successfully."
+      ;;
+    *)
+      notify-send -i error -u critical "KO" "The command $@ failed."
+      ;;
+  esac
+else
+  echo "notify-send is not available."
+  echo "It is available in the 'libnotify-bin' package."
+  return 1
+fi
